/*
 * lcd.h
 *
 *  Created on: 2025年5月9日
 *      Author: mrfra
 */

#ifndef LCD_H_
#define LCD_H_

#define PIC_PIXEL_CURRENCY_WIDTH        24
#define PIC_PIXEL_CURRENCY_HEIGHT       50

#define PIC_PIXEL_CITY_WIDTH            66
#define PIC_PIXEL_CITY_HEIGHT           133

#define PIC_PIXEL_NUM_WIDTH             17
#define PIC_PIXEL_NUM_HEIGHT            8

#define PIC_QSPI_NORMAL    1

#if PIC_QSPI_NORMAL
enum {
    PICTURE_INDEX_POWER_UP = 0,
    PICTURE_INDEX_MAIN_SCREEN,
    PICTURE_INDEX_KIT_INFO,
    PICTURE_INDEX_LED_SCREEN,
    PICTURE_INDEX_CURRENCY,
    PICTURE_INDEX_FACE_DETECT,
    PICTURE_INDEX_IMAGE_CLASS,

    PICTURE_INDEX_WEATHER_SHANGHAI,
    PICTURE_INDEX_WEATHER_KYOTO,
    PICTURE_INDEX_WEATHER_NEW_YORK,
    PICTURE_INDEX_WEATHER_SAN_FRAN,

    PICTURE_INDEX_WORLD_TIME,
    PICTURE_INDEX_SAN_FRANCISCO,
    PICTURE_INDEX_LONDON,
    PICTURE_INDEX_BEIJING,
    PICTURE_INDEX_TOKYO,

    PICTURE_INDEX_CURRENCY_CNY,
    PICTURE_INDEX_CURRENCY_USD,

    PICTURE_INDEX_WEATHER_RAIN,
    PICTURE_INDEX_WEATHER_SNOW,
    PICTURE_INDEX_WEATHER_SUN,
    PICTURE_INDEX_WEATHER_WIND,

    PICTURE_INDEX_POINT,
    PICTURE_INDEX_EQUALS,
    PICTURE_INDEX_NUM_ZERO,
    PICTURE_INDEX_NUM_ONE,
    PICTURE_INDEX_NUM_TWO,
    PICTURE_INDEX_NUM_THREE,
    PICTURE_INDEX_NUM_FOUR,
    PICTURE_INDEX_NUM_FIVE,
    PICTURE_INDEX_NUM_SIX,
    PICTURE_INDEX_NUM_SEVEN,
    PICTURE_INDEX_NUM_EIGHT,
    PICTURE_INDEX_NUM_NINE,

    PICTURE_INDEX_MAX,
};
#else
enum {
    PICTURE_INDEX_CURRENCY = 0,
    PICTURE_INDEX_CURRENCY_USD,
    PICTURE_INDEX_CURRENCY_CNY,
    PICTURE_INDEX_NUM_ZERO,
    PICTURE_INDEX_NUM_ONE,
    PICTURE_INDEX_NUM_TWO,
    PICTURE_INDEX_NUM_THREE,
    PICTURE_INDEX_NUM_FOUR,
    PICTURE_INDEX_NUM_FIVE,
    PICTURE_INDEX_NUM_SIX,
    PICTURE_INDEX_NUM_SEVEN,
    PICTURE_INDEX_NUM_EIGHT,
    PICTURE_INDEX_NUM_NINE,

    PICTURE_INDEX_EQUALS,
    PICTURE_INDEX_POINT,

    PICTURE_INDEX_WORLD_TIME,
    PICTURE_INDEX_SAN_FRANCISCO,
    PICTURE_INDEX_LONDON,
    PICTURE_INDEX_BEIJING,
    PICTURE_INDEX_TOKYO,

    PICTURE_INDEX_WEATHER_SHANGHAI,
    PICTURE_INDEX_WEATHER_KYOTO,

    PICTURE_INDEX_WEATHER_RAIN,
    PICTURE_INDEX_WEATHER_SNOW,
    PICTURE_INDEX_WEATHER_SUN,
    PICTURE_INDEX_WEATHER_WIND,

    PICTURE_INDEX_WEATHER_NEW_YORK,
    PICTURE_INDEX_WEATHER_SAN_FRAN,

    PICTURE_INDEX_POWER_UP,
    PICTURE_INDEX_IMAGE_CLASS,
    PICTURE_INDEX_MAIN_SCREEN,
    PICTURE_INDEX_LED_SCREEN,
    PICTURE_INDEX_KIT_INFO,
    PICTURE_INDEX_FACE_DETECT,

    PICTURE_INDEX_MAX,
};
#endif

uint16_t *lcd_get_pic_from_flash(uint8_t index);
void init_picture_info(void);

#endif /* LCD_H_ */
