/***********************************************************************************************************************
* Copyright (c) 2023 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

/**********************************************************************************************************************
 * File Name    : menu_thread_entry.c
 * Version      : .
 * Description  : The main menu demo thread.
 *********************************************************************************************************************/

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include "menu_thread.h"
#include "menu_main.h"
#include "common_init.h"
#include "common_data.h"
#include "board_cfg.h"
#include "lcd.h"

#define WAIT_TIME    (500u)            /* Wait time for task on Semaphore and Message Queue*/

extern TaskHandle_t key_thread;  /* In key_thread.c, generated by fsp */
extern void key_thread_create(void);

void menu_thread_entry (void * pvParameters)
{
    FSP_PARAMETER_NOT_USED(pvParameters);

    /* Initialse subsystem */
    common_init();

    R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);

    init_picture_info();

    xTaskNotifyGive(key_thread);

    while (1) {
        vTaskDelay(WAIT_TIME);

        main_display_menu();
    }
}
