/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
#include "hal_data.h"
#include "board_sdram.h"
#include <stdio.h>
#include "common_utils.h"
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER



volatile uint32_t DWT_pre_count=0, DWT_post_count=0, time_sdram_access=0;
volatile uint32_t DWT_delta=0;

#define SDRAM_EXAMPLE_DATALEN    32*1024

volatile uint32_t SRAM_write_buff_Cache[SDRAM_EXAMPLE_DATALEN];
volatile uint32_t SRAM_read_buff_Cache[SDRAM_EXAMPLE_DATALEN];

volatile uint32_t sdram_cache[SDRAM_EXAMPLE_DATALEN] BSP_PLACE_IN_SECTION(".sdram");
volatile uint32_t sdram_nocache[SDRAM_EXAMPLE_DATALEN]  BSP_PLACE_IN_SECTION(".nocache_sdram");


/*******************************************************************************
 *
 ******************************************************************************/
#define EXAMPLE_SDRAM_START_ADDRESS (0x68000000U)
#define EXAMPLE_DTCM_START_ADDRESS  (0x20000000U)
#define EXAMPLE_SRAM_START_ADDRESS  (0x220B0000U)


uint8_t timer1s_flag = 0;
/* Callback function */



uint32_t sdram_write_count = 0;
/* SRAM<--->SDRAM 读写测试 */
void SDRAMReadWrite32Bit_test(void)
{
       uint32_t index;
       uint32_t datalen = SDRAM_EXAMPLE_DATALEN ;
       uint32_t i = 0;

       APP_PRINT("##############################################################\r\n");
       APP_PRINT("##############################################################\r\n");
       APP_PRINT("********** Write to SDRAM! **********\r\n");


       memset((uint32_t *)SRAM_write_buff_Cache, 0 ,datalen);
       memset((uint32_t *)SRAM_read_buff_Cache, 0 ,datalen);
       memset((uint32_t *)sdram_cache, 0 ,datalen);
       memset((uint32_t *)sdram_nocache, 0 ,datalen);
       for( i=0; i<datalen; i++)
       {
           SRAM_write_buff_Cache[i] = i;
       }


       for (index = 0; index < datalen; index++)
       {
           sdram_cache[index]  = SRAM_write_buff_Cache[index];  //source 为 SRAM
       }

       APP_PRINT("**********Write SDRAM End! **********\r\n");
       APP_PRINT("**********Write %d bytes to SDRAM  **********\r\n", SDRAM_EXAMPLE_DATALEN*4);

       R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);

       APP_PRINT("##############################################################\r\n");
       APP_PRINT("##############################################################\r\n");
       APP_PRINT("**********Read from SDRAM! **********\r\n");


        for (index = 0; index < datalen; index++)
        {
            SRAM_read_buff_Cache[index] = sdram_cache[index];  //读SDRAM
        }

        index = 0;
        while(index<datalen)
        {
            if(SRAM_read_buff_Cache[index] != SRAM_write_buff_Cache[index])
            {
                APP_PRINT("**********SRDAM test failed **********\r\n");
                while(1)
                {
                    ;
                }
            }
            index++;
        }

        APP_PRINT("**********Read %d bytes from SDRAM  **********\r\n", SDRAM_EXAMPLE_DATALEN*4);
        APP_PRINT("**********SRDAM read End! **********\r\n");
        APP_PRINT("**********SRDAM test pass **********\r\n");


}





/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    APP_PRINT("SDRAM read/write test start!\r\n");
    /* Initialize SDRAM. */
    bsp_sdram_init();          //See BSP_PRV_SDRAM_BUS_WIDTH to define bus width of SDRAM

    SDRAMReadWrite32Bit_test();

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        IOPORT_CFG_OPEN (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
