/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#include "hal_data.h"
#include "ecat_def.h"
#include "ecatappl.h"
#include "ecatslv.h"
#include "applInterface.h"
#if (CiA402_SAMPLE_APPLICATION == 1)
#include "cia402appl.h"
#else
#include "sampleappl.h"
#endif
#include "renesashw.h"


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	fsp_err_t err;

    /* TODO: add your own code here */

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif

	/* Initialize EtherCAT SSC Port */
	err = RM_ETHERCAT_SSC_PORT_Open(gp_ethercat_ssc_port->p_ctrl, gp_ethercat_ssc_port->p_cfg);
	if(FSP_SUCCESS != err)
	{
		__BKPT(0);	/* Can't continue the stack */
	}
	/* Initilize the stack */
	MainInit();
#if (CiA402_SAMPLE_APPLICATION == 1)
	/* Initialize axis structures */
	CiA402_Init();
#endif
	/* Create basic mapping */
	APPL_GenerateMapping(&nPdInputSize,&nPdOutputSize);
	/* Set stack run flag */
	bRunApplication = TRUE;
	/* Execute the stack */
	while(bRunApplication == TRUE)
	{
		MainLoop();
	}
#if (CiA402_SAMPLE_APPLICATION == 1)
	/* Remove all allocated axes resources */
	CiA402_DeallocateAxis();
#endif
	/* Close SSC Port */
	RM_ETHERCAT_SSC_PORT_Close(gp_ethercat_ssc_port->p_ctrl);
}



