/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'LCD' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Acceleration:Arm-2D:Core@1.2.5 */
#define ___ARM_2D_CFG_SKIP_HEADER___
/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.5.2 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1
/* GorgonMeducer::Utilities:perf_counter:Porting&PMU@1.2.1 */
#define __PERFC_USE_PORTING__                           1
#define __PERFC_USE_PMU_PORTING__                       1
#define __PERFC_CFG_DISABLE_DEFAULT_SYSTICK_PORTING__   1
#define __PERFC_CFG_PORTING_INCLUDE__                   "perfc_port_pmu.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
