/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'LCD' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::Acceleration:Arm-2D Extras:Benchmark-Generic@1.5.3 */
#define RTE_Acceleration_Arm_2D_Extra_Benchmark
#define RTE_Acceleration_Arm_2D_Extra_Benchmark_Generic
/* ARM::Acceleration:Arm-2D Extras:Controls@2.15.0 */
#define RTE_Acceleration_Arm_2D_Extra_Controls
/* ARM::Acceleration:Arm-2D Extras:LCD ASCII Printf@3.0.2 */
#define RTE_Acceleration_Arm_2D_Extra_LCD_printf
/* ARM::Acceleration:Arm-2D Helper:Display Adapter@4.1.0 */
#define RTE_Acceleration_Arm_2D_Helper_Disp_Adapter0
#define __RTE_ACCELERATION_ARM_2D_HELPER_DISP_ADAPTER0__  /* this macro is deprecated, please use the macro above in your code */

/* ARM::Acceleration:Arm-2D Helper:PFB@3.2.0 */
#define RTE_Acceleration_Arm_2D_Helper_PFB
/* ARM::Acceleration:Arm-2D:Alpha-Blending@1.2.5 */
#define RTE_Acceleration_Arm_2D_Alpha_Blending
/* ARM::Acceleration:Arm-2D:Core@1.2.5 */
#define RTE_Acceleration_Arm_2D
#define __RTE_ACCELERATION_ARM_2D__     /* this macro is deprecated, please use the macro above in your code */
/* ARM::Acceleration:Arm-2D:Filter@1.2.5 */
#define RTE_Acceleration_Arm_2D_Filter
/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.5.2 */
#define __PERF_COUNTER__ 1
/* GorgonMeducer::Utilities:perf_counter:Porting&PMU@1.2.1 */
#define __RTE_PERFC_PORTING_PMU__ 1


#endif /* RTE_COMPONENTS_H */
