#include "console.h"
#include "hal_data.h"
#include "iic.h"

#include "camera/camera.h"
#include "SEGGER_RTT/SEGGER_RTT.h"
#include "utils/log.h"

#define DEMO_MODE_OV5640	1
#define DEMO_MODE_OV7725	2

#define DEMO_MODE	DEMO_MODE_OV7725

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

#if DEMO_MODE == DEMO_MODE_OV5640
static Camera s_camera_ov5640_dvp;
#else
static Camera s_camera_ov7725;
#endif

static uint8_t s_dvp_image[640 * 480 * 2] __attribute__((aligned(8)));

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	/* TODO: add your own code here */
#if DEMO_MODE == DEMO_MODE_OV5640
	CameraConfig ov5640_config_dvp;
#else
	CameraConfig ov7725_config;
#endif
	uint32_t ret;

	uint8_t capture_cnt = 0;

#if CONSOLE_CFG_USE_RTT == 0
    SEGGER_RTT_Init();
#endif
    CONSOLE_Init();
    LOG_Reset();

    /* Clean screen */
#if CONSOLE_CFG_USE_RTT
    puts(RTT_CTRL_RESET);
    puts(RTT_CTRL_CLEAR);
#else
    puts("\x1b[2J\x1b[H");
    puts("\x1B[0m");
#endif

    IIC_Init();
    R_GPT_Open(g_timer10.p_ctrl, g_timer10.p_cfg);
    R_GPT_Start(g_timer10.p_ctrl);

#if DEMO_MODE == DEMO_MODE_OV5640
    ov5640_config_dvp.model = CAMERA_MODEL_OV5640;
    ov5640_config_dvp.interface = CAMERA_INTERFACE_DVP;
    ov5640_config_dvp.length = g_ceu_ov5640_cfg.x_capture_pixels;
    ov5640_config_dvp.width = g_ceu_ov5640_cfg.y_capture_pixels;
    ov5640_config_dvp.peripheral_inst = &g_ceu_ov5640;
    CameraInit(&s_camera_ov5640_dvp, &ov5640_config_dvp);
    CameraStartCapture(&s_camera_ov5640_dvp, s_dvp_image);
#else
    ov7725_config.model = CAMERA_MODEL_OV7725;
    ov7725_config.interface = CAMERA_INTERFACE_DVP;
    ov7725_config.length = g_ceu_ov7725_cfg.x_capture_pixels;
    ov7725_config.width = g_ceu_ov7725_cfg.y_capture_pixels;
    ov7725_config.peripheral_inst = &g_ceu_ov7725;
    CameraInit(&s_camera_ov7725, &ov7725_config);
    CameraStartCapture(&s_camera_ov7725, s_dvp_image);
#endif

	/* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if DEMO_MODE == DEMO_MODE_OV5640
    ret = CameraIsCaptureDone(&s_camera_ov5640_dvp);
#else
    ret = CameraIsCaptureDone(&s_camera_ov7725);
#endif
    while (capture_cnt < 20) {
    	while (ret == 0) {
    		R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
    	#if DEMO_MODE == DEMO_MODE_OV5640
			ret = CameraIsCaptureDone(&s_camera_ov5640_dvp);
		#else
			ret = CameraIsCaptureDone(&s_camera_ov7725);
		#endif
    	}
    	ret = 0;
    	capture_cnt++;
    }

    __BKPT(0);

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
