/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'arm2d_cpkexp_ra8d1' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Acceleration:Arm-2D:Core@1.2.4 */
#define ___ARM_2D_CFG_SKIP_HEADER___
/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.5.2 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1


#endif /* PRE_INCLUDE_GLOBAL_H */
