/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Entry function.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
 * SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2023 Renesas Electronics Corporation. All rights reserved.
 ***********************************************************************************************************************/
#include "hal_data.h"
#include "common_utils.h"
//#include "wave_data111.h"
#include <stdio.h>
#include "ov7725.h"
#include "ceu.h"
#include "board_sdram.h"
#include "graphics.h"
#include "mipi_dsi_ep.h"

#include "perf_counter/perf_counter.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

uint8_t g_image_vga_sram [ VGA_WIDTH * VGA_HEIGHT * YUV422_BYTE_PER_PIXEL ] ;

extern volatile bool g_vsync_flag;

static uint32_t get_cpu_load(uint32_t total, uint32_t ceu)
{
	if (total <= ceu)
		return 0;

	return ((total - ceu) * 100) / total;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
       /* TODO: add your own code here */
       fsp_err_t err = FSP_SUCCESS;
       /* Initialize SDRAM. */
       bsp_sdram_init();
       uint32_t ms_start = 0, ms_cur;
       uint32_t ceu_used_total = 0, ceu_used;
       uint32_t fps = 0;

       init_cycle_counter(false);

       /* Initialize IIC MASTER module */
        err = R_IIC_MASTER_Open(&g_i2c_master1_ctrl, &g_i2c_master1_cfg);
        /* Handle error */
        if(err != FSP_SUCCESS){
            APP_PRINT( "** IIC MASTER Open API failed ** \r\n");
        }

        #if 1
            /* Initialize OV7725 camera sensor */
            err = ov7725_open();
            /* Handle error */
            if(err != FSP_SUCCESS){
                APP_PRINT( "** ov7725_open API failed ** \r\n");
            }
            OV7725_Window_Set(VGA_WIDTH, VGA_HEIGHT, 1);
        #else
            ov5640_init();
            ov5640_set_output_format(OV5640_OUTPUT_FORMAT_RGB565);
            ov5640_auto_focus_init();
        //    ov5640_set_test_pattern(OV5640_TEST_PATTERN_COLOR_BAR);
            ov5640_set_output_size(VGA_WIDTH,VGA_HEIGHT);
            ov5640_set_exposure_level(OV5640_EXPOSURE_LEVEL_8);
        #endif

            err = ceu_init(g_image_vga_sram, VGA_WIDTH, VGA_HEIGHT);
            /* Handle error */
            if(err != FSP_SUCCESS ){
                APP_PRINT( "** ceu_init API failed ** \r\n");
            }

            graphics_init();

            mipi_dsi_entry();

            gp_frame_buffer = gp_single_buffer;

       while(1){
            if (ms_start == 0)
                ms_start = (uint32_t)get_system_ms();

            /* Swap the active framebuffer */
            gp_frame_buffer = (gp_frame_buffer == gp_single_buffer) ? gp_double_buffer : gp_single_buffer;
            err = ceu_operation(g_image_vga_sram, &ceu_used);
            ceu_used_total += ceu_used;
            /* Handle error */
            if(err != FSP_SUCCESS ){
                APP_PRINT( "** ceu_operation API failed ** \r\n");
            }

#if(0)
            yuv422_to_rgb565(&g_image_vga_sram[0], &g_image_rgb565_sdram_buffer[0], VGA_WIDTH, VGA_HEIGHT);
            //            YUVtoRGB565(&g_image_vga_sram[0], &g_image_rgb565_sdram_buffer[0], VGA_WIDTH, VGA_HEIGHT);
            //            yuv422_to_rgb888(&g_image_vga_sram[0], &g_image_rgb565_sdram_buffer[0], VGA_WIDTH, VGA_HEIGHT);
            graphics_draw_frame(&g_image_rgb565_sdram_buffer[0], (uint8_t*) gp_frame_buffer, VGA_WIDTH, VGA_WIDTH, VGA_HEIGHT);
#else
            graphics_draw_frame(&g_image_vga_sram[0], (uint8_t*) gp_frame_buffer, VGA_WIDTH, VGA_WIDTH, VGA_HEIGHT);
#endif

            /* Now that the framebuffer is ready, update the GLCDC buffer pointer on the next Vsync */
            R_GLCDC_BufferChange (&g_display_ctrl, (uint8_t*) gp_frame_buffer, DISPLAY_FRAME_LAYER_1);
            fps++;

            ms_cur = get_system_ms();
            if (ms_cur - ms_start >= 1000) {
                APP_PRINT("CEU fps %u (%u x %u) cpu_load %u%%\n",
				fps * 1000 / (ms_cur - ms_start), VGA_WIDTH, VGA_HEIGHT,
				get_cpu_load(ms_cur - ms_start, ceu_used_total));
                fps = 0;
                ms_start = 0;
		ceu_used_total = 0;
            }

            /* Wait for a Vsync event */
            g_vsync_flag = RESET_FLAG;
            while (g_vsync_flag);
       }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}


/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }

}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
