/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#include "hal_data.h"
#include <math.h>

#define SAMPLE_COUNT 180

volatile bool adc_complete_flag = false;

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
	// comment added by Jin for test
    fsp_err_t status;
    uint16_t var[SAMPLE_COUNT];
    uint16_t adc_result[SAMPLE_COUNT];
    uint32_t i;

    for(i=0; i<SAMPLE_COUNT; i++)
    {
        var[i] = (uint16_t)(4*1024*(float)sin(i*2*M_PI/SAMPLE_COUNT));
    }

    status = R_DAC_Open(&g_dac0_ctrl, &g_dac0_cfg);
    if(FSP_SUCCESS != status)
    {
        while(1);
    }

    status = R_DAC_Start(&g_dac0_ctrl);
    if(FSP_SUCCESS != status)
    {
        while(1);
    }

    status = R_ADC_Open(&g_adc0_ctrl, &g_adc0_cfg);
    if(FSP_SUCCESS != status)
    {
        while(1);
    }

    status = R_ADC_ScanCfg(&g_adc0_ctrl, &g_adc0_channel_cfg);
    if(FSP_SUCCESS != status)
    {
        while(1);
    }

    while(1)
    {
        for(i=0; i<SAMPLE_COUNT; i++)
        {
            status = R_DAC_Write(&g_dac0_ctrl, var[i]);
            if(FSP_SUCCESS != status)
            {
                while(1);
            }

            R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);

            status = R_ADC_ScanStart(&g_adc0_ctrl);
            if(FSP_SUCCESS != status)
            {
                while(1);
            }

            while(false == adc_complete_flag);
            adc_complete_flag = false;

            status = R_ADC_Read(&g_adc0_ctrl, ADC_CHANNEL_0, &adc_result[i]);
            if(FSP_SUCCESS != status)
            {
                while(1);
            }
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/* Callback function */
void user_adc_callback(adc_callback_args_t *p_args)
{
    /* TODO: add your own code here */
    if(ADC_EVENT_SCAN_COMPLETE == p_args->event)
    {
        adc_complete_flag = true;
    }
}
